# Settings for Daedalus GRF

[mcu]
address = "tcp://localhost"
port = 5555

[tcu]
address = "tcp://localhost"
port = 5556

[influx]
address = "tcp://localhost"
port = 5557
org = "myorg"
bucket = "myexperiment"
token = "mytoken"

[restapi]
resturl1 = "http://localhost:8678"
resturl2 = "http://localhost:8679"

[gas]
species = "Ar"
