# Settings for Daedalus TCU

[tcu]
address = "tcp://*"
port = 5555
update_rate = 2 # in seconds

[lakeshore]
sensor1 = "KRDG?A"
sensor2 = "KRDG?B"
address = "192.168.207.120"
port = 7777

[maxigauge]
address = "192.168.207.167"
port = 8000
